name: Deploy Docker Image to ECR 

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    name: Build Image 
    runs-on: ubuntu-latest

    steps: 
    - name: check out code 
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-dev-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx create --use 
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .


  deploy:
    name: Ansible Deploy to EC2 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Ansible + collections
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-core boto3 botocore 
          ansible-galaxy collection install amazon.aws community.docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Reconstruct SSH key (from base64) and verify
        run: |
          set -euo pipefail
          echo "${{ secrets.EC2_SSH_KEY_B64 }}" | base64 -d > ./my-new-ans-key
          chmod 600 ./my-new-ans-key
          ssh-keygen -lf ./my-new-ans-key


      - name: Run Ansible Playbook
        env:
          IMAGE_TAG: ${{ github.sha }}
          AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION:  ${{ env.AWS_DEFAULT_REGION }}
          EC2_USER: ${{ secrets.EC2_USER }} 
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            --private-key ./my-new-ans-key \
            -u ${{ secrets.EC2_USER }} \
            -e "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -e "image_tag=${IMAGE_TAG}" -vv