name: Deploy Docker Image to ECR 

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    name: Build Image 
    runs-on: ubuntu-latest

    steps: 
    - name: Check out code 
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build & push
      run: |
        docker buildx create --use
        docker buildx build \
        --platform linux/amd64,linux/arm64 \
        -t "${{ steps.ecr.outputs.registry }}/my-dev-ecr-repo:${{ github.sha }}" \
        --push .

    - name: Trigger Repo B deploy with this image tag
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_B_DISPATCH_TOKEN }}
        repository: sae-org/ansible-controller-config   # Repo B
        event-type: deploy-from-repo-a
        client-payload: >-
          {"image_tag":"${{ github.sha }}",
            "ecr_repo":"my-dev-ecr-repo",
            "region":"us-east-1",
            "aws_account_id":"${{ secrets.AWS_ACCOUNT_ID }}"}
