name: Deploy Docker Image to ECR - 

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    name: Build Image 
    runs-on: ubuntu-latest

    steps: 
    - name: Check out code 
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-dev-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx create --use 
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .

    - name: Write controller SSH key & trust host
      run: |
        mkdir -p ~/.ssh
        printf '%s' "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > ~/.ssh/controller.pem
        chmod 600 ~/.ssh/controller.pem
        ssh-keyscan -H "${{ secrets.ANSIBLE_HOST }}" >> ~/.ssh/known_hosts

    - name: Pull Repo B (ansible-controller-config) code, deploy and then run Ansible Playbook
      env:
        IMAGE_TAG: ${{ github.sha }} 
        REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}       
      run: |
        ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no \
        -i ~/.ssh/controller.pem \
          ${{ secrets.EC2_USER }}@${{ secrets.ANSIBLE_HOST }} "
            set -euo pipefail
            cd /home/ubuntu

            # Use HTTPS with token instead of SSH
            if [ -d projects/.git ]; then
              git -C ansible pull --ff-only
            else
              git clone https://${REPO_B_TOKEN}@github.com/sae-org/ansible-controller-config.git projects
            fi

            cd projects/ansible
            ansible-playbook playbooks/deploy.yml \
              -e aws_account_id='${{ secrets.AWS_ACCOUNT_ID }}' \
              -e ecr_repo='my-dev-ecr-repo' \
              -e image_tag='${IMAGE_TAG}'
        "