name: Deploy Docker Image to ECR 

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    name: Build Image 
    runs-on: ubuntu-latest

    steps: 
    - name: check out code 
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-dev-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx create --use 
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .


  deploy:
    name: Ansible Deploy to EC2 
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Ansible + collections
        run: |
          python3 -m pip install --upgrade pip
          pip install ansible-core
          ansible-galaxy collection install amazon.aws community.docker

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > my_ec2_key
          chmod 600 my_ec2_key

      # - name: Add EC2 host key to known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          ansible-playbook -i ansible/inventory_aws_ec2.yml ansible/deploy.yml \
            --private-key ./my_ec2_key \
            -u ${{ secrets.EC2_USER }} \
            -e "aws_account_id=${{ secrets.AWS_ACCOUNT_ID }}" \
            -e "image_tag=${IMAGE_TAG}"