name: Deploy Docker Image to ECR 

on: 
  push: 
    branches: [ main ]
  
jobs: 
  build: 
    name: Build Image 
    runs-on: ubuntu-latest

    steps: 
    - name: check out code 
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with: 
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: my-dev-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx create --use 
        docker buildx build --platform linux/amd64,linux/arm64 -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --push .


    - name: Add controller SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.CONTROLLER_SSH_KEY }}" > ~/.ssh/controller.pem
        chmod 600 ~/.ssh/controller.pem

    - name: Run Ansible Playbook
      env:
        IMAGE_TAG: ${{ github.sha }}           
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/controller.pem \
        ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
        "cd ~/ansible && \
        ansible-playbook playbooks/deploy.yml \
          -e aws_account_id='${{ secrets.AWS_ACCOUNT_ID }}' \
          -e image_tag='${IMAGE_TAG}'"
        